LangString addOrReinstall ${LANG_SIMPCHINESE} "覆盖安装"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "${PRODUCTNAME} ${VERSION} 已安装。请选择要执行的操作，然后单击下一步。"
LangString appRunning ${LANG_SIMPCHINESE} "{{product_name}} 正在运行，请关闭后重试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "{{product_name}} 正在运行。$\n单击确定结束程序。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "选择维护方式。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "选择 ${PRODUCTNAME} 的安装方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "覆盖安装（保留用户数据）"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "不能直接覆盖降级，请先卸载当前版本"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法结束 {{product_name}}，请关闭后重试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 WebView2..."
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "检测到更新版本的 ${PRODUCTNAME}。安装旧版本可能导致兼容问题，请选择安装方式。"
LangString older ${LANG_SIMPCHINESE} "较旧"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "检测到 $R4 版本的 ${PRODUCTNAME}。覆盖安装会保留用户数据。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "静默模式不允许直接降级，请使用图形安装界面。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载。"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "卸载后安装"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "WebView2 安装失败，${PRODUCTNAME} 无法运行。请重启安装程序。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "WebView2 下载失败：$0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 下载完成"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2..."
LangString webview2InstallError ${LANG_SIMPCHINESE} "WebView2 安装失败，错误代码：$1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "WebView2 安装完成"
LangString deleteAppData ${LANG_SIMPCHINESE} "清除用户数据"
